name: Update Dockerfile

on:
  push:
    branches: ["branchHTTPservMulti"]
  pull_request:
    branches: ["branchHTTPservMulti"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build contexts
        run: docker buildx ls  # Check available platforms

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # First, build and push images for both architectures
      - name: Build and push the Docker image for amd64
        if: ${{ matrix.architecture == 'amd64' }}
        run: |
          docker build --platform=linux/amd64 \
            -t skhtskiryna/my-http-server:amd64 --push .
      - name: Build and push the Docker image for arm64
        if: ${{ matrix.architecture == 'arm64' }}
        run: |
          docker build --platform=linux/arm64 \
            -t skhtskiryna/my-http-server:arm64 --push .
      # Add a delay to allow images to be fully pushed and available on Docker Hub
      - name: Wait for images to be fully pushed
        run: sleep 30  # Sleep for 30 seconds to allow images to propagate on Docker Hub

      # After building, verify if the images exist
      - name: Verify amd64 image is available
        run: |
          docker pull skhtskiryna/my-http-server:amd64 || echo "amd64 image not found"
      - name: Verify arm64 image is available
        run: |
          docker pull skhtskiryna/my-http-server:arm64 || echo "arm64 image not found"
      # Now, after verification, create and push the multi-architecture manifest
      - name: Create and push multi-architecture manifest
        if: ${{ success() }}
        run: |
          echo "Creating multi-architecture manifest..."
          docker manifest create skhtskiryna/my-http-server:latest \
            --amend skhtskiryna/my-http-server:amd64 \
            --amend skhtskiryna/my-http-server:arm64
          
          # Push the multi-architecture manifest
          docker manifest push skhtskiryna/my-http-server:latest
