name: Asynchronous calls

on:
  push:
    branches:
      - "branchHTTPservMulti"
  pull_request:
    branches:
      - "branchHTTPservMulti"

jobs:
  test-response-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Start HTTP Server
        run: |
          nohup ./program > server.log 2>&1 &
          echo $! > server.pid
          # Wait until the server is available
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8081 > /dev/null; then
              echo "Server is up and running!"
              break
            fi
            echo "Waiting for server to start..."
            sleep 1
          done

      - name: Run scriptB
        run: |
          chmod +x scriptB.sh
          ./scriptB.sh > response_times.log &

      - name: Analyze response times
        run: |
          if grep -E "Response time: [2-9][0-9]{3} ms" response_times.log; then
            echo "High response time detected!"
            exit 1
          else
            echo "All response times are within acceptable limits."
          fi

      - name: Stop server
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid)
            echo "Server stopped successfully."
          else
            echo "Server PID not found. Ensure the server is stopped."
          fi

