name: Build Multistage

on:
  push:
    branches: ["branchHTTPserver"]
  pull_request:
    branches: ["branchHTTPserver"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name:  Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build contexts
        run: docker buildx ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        run: |
          docker build --platform linux/${{ matrix.architecture }} \
            -t skhtskiryna/my-http-server:${{ matrix.architecture }} --push .

      - name: Create and push manifest
        run: |
          docker manifest create skhtskiryna/my-http-server:latest \
            --amend skhtskiryna/my-http-server:amd64 \
            --amend skhtskiryna/my-http-server:arm64
          docker manifest push skhtskiryna/my-http-server:latest
