name: Build Multistage

on:
  push:
    branches: ["branchHTTPserver"]
  pull_request:
    branches: ["branchHTTPserver"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build contexts
        run: docker buildx ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} \
            -t skhtskiryna/my-http-server:${{ matrix.architecture }} --push .

      # Only create the manifest after both architectures are built
      - name: Create and push manifest
        if: ${{ matrix.architecture == 'amd64' }}  # Run this only after the `amd64` image is built
        run: |
          # Wait for the amd64 and arm64 images to be pushed
          echo "Waiting for both images to be available on Docker Hub..."
          sleep 30  # Optional: Adjust sleep time if needed
          
          # Create a multi-architecture manifest list
          docker manifest create skhtskiryna/my-http-server:latest \
            --platform linux/amd64 skhtskiryna/my-http-server:amd64 \
            --platform linux/arm64 skhtskiryna/my-http-server:arm64

          # Push the multi-architecture manifest list to Docker Hub
          docker manifest push skhtskiryna/my-http-server:latest
