name: Build Multistage

on:
  push:
    branches: ["branchHTTPserver"]
  pull_request:
    branches: ["branchHTTPserver"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build contexts
        run: docker buildx ls 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} \
            -t skhtskiryna/my-http-server:${{ matrix.architecture }} --push .

      # Wait for both amd64 and arm64 images to be available on Docker Hub
      - name: Check if amd64 image is available
        run: |
          docker pull skhtskiryna/my-http-server:amd64 || echo "amd64 image not found"

      - name: Check if arm64 image is available
        run: |
          docker pull skhtskiryna/my-http-server:arm64 || echo "arm64 image not found"

      # Wait for both amd64 and arm64 images to be available on Docker Hub
      - name: Wait for both images to be available on Docker Hub
        if: ${{ matrix.architecture == 'arm64' }}
        run: |
          echo "Waiting for both images to be available on Docker Hub..."
          sleep 30  # За потреби налаштуйте час затримки

      # Create and push multi-architecture manifest
      - name: Create and push multi-architecture manifest
        if: ${{ matrix.architecture == 'arm64' }}  
        run: |
          # Create a multi-architecture manifest
          docker manifest create skhtskiryna/my-http-server:latest \
            --amend skhtskiryna/my-http-server:amd64 \
            --amend skhtskiryna/my-http-server:arm64

          # Push the multi-architecture manifest to Docker Hub
          docker manifest push skhtskiryna/my-http-server:latest
