name: Build Multistage

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build contexts
        run: docker buildx ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image for amd64
        if: ${{ matrix.architecture == 'amd64' }}
        run: |
          docker buildx build --platform linux/amd64 \
            -t skhtskiryna/my-http-server:amd64 --push .

      - name: Build and push the Docker image for arm64
        if: ${{ matrix.architecture == 'arm64' }}
        run: |
          docker buildx build --platform linux/arm64 \
            -t skhtskiryna/my-http-server:arm64 --push .

      - name: Check if amd64 image is available
        run: |
          docker pull skhtskiryna/my-http-server:amd64 || echo "amd64 image not found"
        
      - name: Check if arm64 image is available
        run: |
          docker pull skhtskiryna/my-http-server:arm64 || echo "arm64 image not found"

      - name: Create and push multi-architecture manifest
        if: ${{ success() }}
        run: |
          echo "Creating multi-architecture manifest..."
          docker manifest create skhtskiryna/my-http-server:latest \
            --amend skhtskiryna/my-http-server:amd64 \
            --amend skhtskiryna/my-http-server:arm64
          docker manifest push skhtskiryna/my-http-server:latest
