name: Test scriptA

on:
  push:
    branches: ["branchHTTPservMulti"]
  pull_request:
    branches: ["branchHTTPservMulti"]

jobs:
  test-scriptA:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker environment
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install required dependencies
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc

      # Grant execution permissions to the script
      - name: Make script executable
        run: chmod +x scriptA.sh

      # Execute the script
      - name: Run Docker management script
        run: ./scriptA.sh
