name: Test CI

on:
  push:
    branches: [ "branchHTTPserver" ]
  pull_request:
    branches: [ "branchHTTPserver" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev cmake

      - name: Build
        run: |
          aclocal
          autoconf
          automake --add-missing
          ./configure
          cmake .
          make

      - name: Run tests
        run: |
          ./tests/main_test || exit 1

      - name: Build Docker image
        run: |
          echo "FROM alpine" > Dockerfile
          echo "MAINTAINER foxira242@gmail.com" >> Dockerfile
          echo "WORKDIR /home/app" >> Dockerfile
          echo "./program ." >> Dockerfile
          echo "apk add libstdc++" >> Dockerfile
          echo "apk add libc6-compat" >> Dockerfile
          echo "ENTRYPOINT ["./program"]" >> Dockerfile
          docker build -t my-http-server .

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.skhtskiryna }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push Docker image
        run: docker push skhtskiryna/my-http-server:latest
